### ISSUE TITLE
Any issue with updating to newer Dart semantics?

### ISSUE THREAD

**Issue by matanlurey** [google/ansicolor-dart#10]
i.e. style guide updates, and then eventually bump to 1.0.0 stable?

(Happy to help out here)

**Comment by jtmcdole** [comment]
That's actually a good idea. I'll try to take a look at it today or
tomorrow.  I'm surprised to see people using the package!

**Comment by jtmcdole** [comment]
@matanlurey

**Comment by jtmcdole** [comment]
If this is what you are looking for, let me know and I'll push it.

**Comment by pulyaevskiy** [comment]
Just a friendly 👉 @matanlurey :)
