### ISSUE TITLE
An opportunity to collaborate w/ pkg:io ?

### ISSUE THREAD

**Issue by kevmoo** [google/ansicolor-dart#16]
We have basic ansi support: https://github.com/dart-lang/io/blob/master/lib/src/ansi_code.dart

Would be interesting to combine efforts and reduce duplication?

**Comment by jtmcdole** [comment]
SGTM

I think this could still be somewhat useful in chrome logs as well, since you can colorize the console:
`console.log('%c Oh my heavens! ', 'background: #222; color: #bada55');`

**Comment by kevmoo** [comment]
Cool! didn't know that was an option in Chrome.

If you have thoughts on pkg:io, let us know...

**Comment by jtmcdole** [comment]
Closing a long old issue.  One thing I'd love from pkg:io/dart:io is the ability to interact with the terminal more (mouse input, sizing, better reverse CSI handling).
