### ISSUE TITLE
Stopped working after update

### ISSUE THREAD

**Issue by temirfe** [google/ansicolor-dart#22]
I was using version 1.0.2, then I updated to version 1.1.1 and it stopped working (i.e. the letters are not colored).

-Reverted this project back to version 1.0.2, run a `flutter clean`, run project - not working.
-Created a new flutter project with only this package (v 1.1.1) - doesn't work.
-Installed other alternative ansi styling packages - they also not working now
-Opened my another project that was using version 1.0.2 - working ok.

here is my flutter doctor:

[✓] Flutter (Channel stable, 1.22.5, on macOS 11.1 20C69 darwin-x64, locale en)
    • Flutter version 1.22.5 at /Users/tema/programs/flutter
    • Framework revision 7891006299 (5 weeks ago), 2020-12-10 11:54:40 -0800
    • Engine revision ae90085a84
    • Dart version 2.10.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/tema/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Users/tema/Library/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✗] Xcode - develop for iOS and macOS
    ✗ Xcode installation is incomplete; a full installation is necessary for iOS
      development.
      Download at: https://developer.apple.com/xcode/download/
      Or install Xcode via the App Store.
      Once installed, run:
        sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
        sudo xcodebuild -runFirstLaunch
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin
        code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To install:
        sudo gem install cocoapods

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.1

[✓] Connected device (1 available)
    • Redmi Go (mobile) • 192.168.88.230:5555 • android-arm • Android 8.1.0 (API
      27)

**Comment by jtmcdole** [comment]
If color isn't showing up; try forcing `ansiColorDisabled = false;`  We use the VM's `stdout.supportsAnsiEscapes` to see if ansi escape codes are supported, but you can force it.

**Comment by temirfe** [comment]
Thank you, it's working now. This is an important notice, I think it should be added in Readme page. Example page has it but I didn't pay attention.

**Comment by jtmcdole** [comment]
Done - thank you for the feedback!
