### ISSUE TITLE
Documentation Error (Example in README Doesn't Work)

### ISSUE THREAD

**Issue by GZGavinZhao** [google/ansicolor-dart#25]
Small error, but perhaps could cause a great amount of bewildering for beginners:

In the [example](https://github.com/google/ansicolor-dart/blob/master/README.md#example) with a background as a peach, foreground as white, `rgb(r: 1.0, g: 0.8, b: 0.2)` should be `rgb(r: 1.0, g: 0.8, b: 0.2, bg = true)`, otherwise it will be recognized as a foreground color.

**Comment by mateusfccp** [comment]
Can this be closed?
